name: MX4300 NSS Build

on: workflow_dispatch

jobs:
    build:
        name: MX4300 NSS Build
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Install packages
              run: |
                  sudo apt-get update && \
                  sudo apt install -y build-essential \
                  clang \
                  flex \
                  bison \
                  g++ \
                  gawk \
                  gcc-multilib \
                  g++-multilib \
                  gettext \
                  git \
                  libncurses5-dev \
                  libssl-dev \
                  python3-setuptools \
                  rsync \
                  swig \
                  unzip \
                  zlib1g-dev \
                  file \
                  wget && \
                  sudo apt-get clean
            - name: Checkout
              uses: actions/checkout@v4

            - name: Update scripts
              run:  ./scripts/feeds update

            - name: Install scripts
              run:  ./scripts/feeds install -a
              
            - name: Install scripts again to check for warnings
              run:  ./scripts/feeds install -a
              
            - name: Fix telephony Makefile
              run: sed -i 's/\([[:space:]]*\)libpcre \\/\1libpcre2 \\/' ./package/feeds/telephony/freeswitch/Makefile
              
            - name: Update scripts again for sanity
              run:  ./scripts/feeds update

            - name: Install scripts again for sanity
              run:  ./scripts/feeds install -a

            - name: Generate config
              run:  cp nss-setup/config-nss.seed .config

            - name: Generate MX4300 NSS config with adblock
              run: cp nss-setup/config-nss.seed .config 
               && sed -i 's/# CONFIG_TARGET_qualcommax_ipq807x_DEVICE_linksys_mx4300 is not set/CONFIG_TARGET_qualcommax_ipq807x_DEVICE_linksys_mx4300=y/g' .config
               && echo "CONFIG_PACKAGE_luci-app-adblock=y" >> .config

            - name: Print initial config we are using
              run: cat .config

            - name: Generate full config
              run:  make defconfig V=s

            - name: Print config again to check
              run: cat .config

            - name: Pre-download
              run: make download -j$(nproc)

            - name: Build firmware images
              run: make -j$(($(nproc)+1))

            - name: Set current date as env variable
              run: echo "CUR_DATE=$(date +'%Y-%m-%d-T%H%M')" >> $GITHUB_ENV

            - name: Get SHA
              uses: benjlevesque/short-sha@v2.2
              
            - name: Release
              uses: ncipollo/release-action@v1
              with:
                tag: MX4300-NSS--${{ env.CUR_DATE }}--${{ env.SHA }}
                artifacts: bin/targets/qualcommax/ipq807x/*.bin